parameters:
    app_env: '%env(APP_ENV)%'
    app_version: '%env(APP_VERSION)%'
    locale: fr

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\DataFixtures\AppFixtures:
        arguments:
            $adminPassword: '%env(ADMIN_PASSWORD)%'