parameters:
    locale: fr
    app_env: '%env(APP_ENV)%'
    app_version: '%env(APP_VERSION)%'
    admin_password: '%env(ADMIN_PASSWORD)%'
    default_from_email: '%env(DEFAULT_FROM_EMAIL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $defaultFromEmail: '%default_from_email%'
            $adminPassword: '%admin_password%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'